/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedLayoutRouteRouteImport } from './routes/_authenticated-layout/route'
import { Route as AuthLayoutRouteRouteImport } from './routes/_auth-layout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLayoutMainLayoutRouteRouteImport } from './routes/_authenticated-layout/_main-layout/route'
import { Route as AuthenticatedLayoutOnboardingIndexRouteImport } from './routes/_authenticated-layout/onboarding/index'
import { Route as AuthLayoutSignupIndexRouteImport } from './routes/_auth-layout/signup/index'
import { Route as AuthLayoutLoginIndexRouteImport } from './routes/_auth-layout/login/index'
import { Route as AuthenticatedLayoutMainLayoutProfileIndexRouteImport } from './routes/_authenticated-layout/_main-layout/profile/index'
import { Route as AuthenticatedLayoutMainLayoutFeedIndexRouteImport } from './routes/_authenticated-layout/_main-layout/feed/index'
import { Route as AuthenticatedLayoutMainLayoutChatIndexRouteImport } from './routes/_authenticated-layout/_main-layout/chat/index'

const AuthenticatedLayoutRouteRoute =
  AuthenticatedLayoutRouteRouteImport.update({
    id: '/_authenticated-layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLayoutRouteRoute = AuthLayoutRouteRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutMainLayoutRouteRoute =
  AuthenticatedLayoutMainLayoutRouteRouteImport.update({
    id: '/_main-layout',
    getParentRoute: () => AuthenticatedLayoutRouteRoute,
  } as any)
const AuthenticatedLayoutOnboardingIndexRoute =
  AuthenticatedLayoutOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedLayoutRouteRoute,
  } as any)
const AuthLayoutSignupIndexRoute = AuthLayoutSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutLoginIndexRoute = AuthLayoutLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthenticatedLayoutMainLayoutProfileIndexRoute =
  AuthenticatedLayoutMainLayoutProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedLayoutMainLayoutRouteRoute,
  } as any)
const AuthenticatedLayoutMainLayoutFeedIndexRoute =
  AuthenticatedLayoutMainLayoutFeedIndexRouteImport.update({
    id: '/feed/',
    path: '/feed/',
    getParentRoute: () => AuthenticatedLayoutMainLayoutRouteRoute,
  } as any)
const AuthenticatedLayoutMainLayoutChatIndexRoute =
  AuthenticatedLayoutMainLayoutChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => AuthenticatedLayoutMainLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/': typeof AuthLayoutLoginIndexRoute
  '/signup/': typeof AuthLayoutSignupIndexRoute
  '/onboarding/': typeof AuthenticatedLayoutOnboardingIndexRoute
  '/chat/': typeof AuthenticatedLayoutMainLayoutChatIndexRoute
  '/feed/': typeof AuthenticatedLayoutMainLayoutFeedIndexRoute
  '/profile/': typeof AuthenticatedLayoutMainLayoutProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLayoutLoginIndexRoute
  '/signup': typeof AuthLayoutSignupIndexRoute
  '/onboarding': typeof AuthenticatedLayoutOnboardingIndexRoute
  '/chat': typeof AuthenticatedLayoutMainLayoutChatIndexRoute
  '/feed': typeof AuthenticatedLayoutMainLayoutFeedIndexRoute
  '/profile': typeof AuthenticatedLayoutMainLayoutProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth-layout': typeof AuthLayoutRouteRouteWithChildren
  '/_authenticated-layout': typeof AuthenticatedLayoutRouteRouteWithChildren
  '/_authenticated-layout/_main-layout': typeof AuthenticatedLayoutMainLayoutRouteRouteWithChildren
  '/_auth-layout/login/': typeof AuthLayoutLoginIndexRoute
  '/_auth-layout/signup/': typeof AuthLayoutSignupIndexRoute
  '/_authenticated-layout/onboarding/': typeof AuthenticatedLayoutOnboardingIndexRoute
  '/_authenticated-layout/_main-layout/chat/': typeof AuthenticatedLayoutMainLayoutChatIndexRoute
  '/_authenticated-layout/_main-layout/feed/': typeof AuthenticatedLayoutMainLayoutFeedIndexRoute
  '/_authenticated-layout/_main-layout/profile/': typeof AuthenticatedLayoutMainLayoutProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/signup/'
    | '/onboarding/'
    | '/chat/'
    | '/feed/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/chat'
    | '/feed'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_auth-layout'
    | '/_authenticated-layout'
    | '/_authenticated-layout/_main-layout'
    | '/_auth-layout/login/'
    | '/_auth-layout/signup/'
    | '/_authenticated-layout/onboarding/'
    | '/_authenticated-layout/_main-layout/chat/'
    | '/_authenticated-layout/_main-layout/feed/'
    | '/_authenticated-layout/_main-layout/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  AuthenticatedLayoutRouteRoute: typeof AuthenticatedLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated-layout': {
      id: '/_authenticated-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated-layout/_main-layout': {
      id: '/_authenticated-layout/_main-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutMainLayoutRouteRouteImport
      parentRoute: typeof AuthenticatedLayoutRouteRoute
    }
    '/_authenticated-layout/onboarding/': {
      id: '/_authenticated-layout/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedLayoutOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRouteRoute
    }
    '/_auth-layout/signup/': {
      id: '/_auth-layout/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthLayoutSignupIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_auth-layout/login/': {
      id: '/_auth-layout/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLayoutLoginIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authenticated-layout/_main-layout/profile/': {
      id: '/_authenticated-layout/_main-layout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedLayoutMainLayoutProfileIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutMainLayoutRouteRoute
    }
    '/_authenticated-layout/_main-layout/feed/': {
      id: '/_authenticated-layout/_main-layout/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof AuthenticatedLayoutMainLayoutFeedIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutMainLayoutRouteRoute
    }
    '/_authenticated-layout/_main-layout/chat/': {
      id: '/_authenticated-layout/_main-layout/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedLayoutMainLayoutChatIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutMainLayoutRouteRoute
    }
  }
}

interface AuthLayoutRouteRouteChildren {
  AuthLayoutLoginIndexRoute: typeof AuthLayoutLoginIndexRoute
  AuthLayoutSignupIndexRoute: typeof AuthLayoutSignupIndexRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutLoginIndexRoute: AuthLayoutLoginIndexRoute,
  AuthLayoutSignupIndexRoute: AuthLayoutSignupIndexRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

interface AuthenticatedLayoutMainLayoutRouteRouteChildren {
  AuthenticatedLayoutMainLayoutChatIndexRoute: typeof AuthenticatedLayoutMainLayoutChatIndexRoute
  AuthenticatedLayoutMainLayoutFeedIndexRoute: typeof AuthenticatedLayoutMainLayoutFeedIndexRoute
  AuthenticatedLayoutMainLayoutProfileIndexRoute: typeof AuthenticatedLayoutMainLayoutProfileIndexRoute
}

const AuthenticatedLayoutMainLayoutRouteRouteChildren: AuthenticatedLayoutMainLayoutRouteRouteChildren =
  {
    AuthenticatedLayoutMainLayoutChatIndexRoute:
      AuthenticatedLayoutMainLayoutChatIndexRoute,
    AuthenticatedLayoutMainLayoutFeedIndexRoute:
      AuthenticatedLayoutMainLayoutFeedIndexRoute,
    AuthenticatedLayoutMainLayoutProfileIndexRoute:
      AuthenticatedLayoutMainLayoutProfileIndexRoute,
  }

const AuthenticatedLayoutMainLayoutRouteRouteWithChildren =
  AuthenticatedLayoutMainLayoutRouteRoute._addFileChildren(
    AuthenticatedLayoutMainLayoutRouteRouteChildren,
  )

interface AuthenticatedLayoutRouteRouteChildren {
  AuthenticatedLayoutMainLayoutRouteRoute: typeof AuthenticatedLayoutMainLayoutRouteRouteWithChildren
  AuthenticatedLayoutOnboardingIndexRoute: typeof AuthenticatedLayoutOnboardingIndexRoute
}

const AuthenticatedLayoutRouteRouteChildren: AuthenticatedLayoutRouteRouteChildren =
  {
    AuthenticatedLayoutMainLayoutRouteRoute:
      AuthenticatedLayoutMainLayoutRouteRouteWithChildren,
    AuthenticatedLayoutOnboardingIndexRoute:
      AuthenticatedLayoutOnboardingIndexRoute,
  }

const AuthenticatedLayoutRouteRouteWithChildren =
  AuthenticatedLayoutRouteRoute._addFileChildren(
    AuthenticatedLayoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  AuthenticatedLayoutRouteRoute: AuthenticatedLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
